### ISSUE TITLE
usability: double click on flows should open the file in spyder, and add edit auto_script in the pop-up menue

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#100]
![doubleclick_flow](https://user-images.githubusercontent.com/75318923/119109391-6b311d00-ba21-11eb-8883-15425eb7f125.jpg)

![flow_edit](https://user-images.githubusercontent.com/75318923/119109408-6ec4a400-ba21-11eb-9849-7408259b90d1.jpg)

**Comment by Zlin526F** [comment]
If #122 implemented, the function: 'double click on flows should open the file in spyder' is not necessary. Only a nice to have.

**Comment by awinia-github** [comment]
#173
