### ISSUE TITLE
sys:1: ResourceWarning after mqtt send:  {"terminate": {"type": "cmd", "command": "terminate",  "sites": ["0"]}

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#108]
after terminate following Warnings occurs:

sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x2082cb2d9a0>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x2082c0b3460>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x2082c0b3ac0>
ResourceWarning: Enable tracemalloc to get the object allocation traceback

**Comment by nerohmot** [comment]
@Slin526F : can you elaborate a bit more?

**Comment by Zlin526F** [comment]
I will close this issue. I think this is a problem with the logger as I use it in my used instruments. When I make a simple example, I don't get an error message. I need to debug further.
