### ISSUE TITLE
after first installation and open an existing project, the target combo box is empty

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#111]
after first installation and open an existing project, the target combo box is empty
![target_empty](https://user-images.githubusercontent.com/75318923/141796859-e9c3d9d4-eaf5-4b36-9a51-e68e61d774e4.png)

You have to restart Spyder  and than the target is ok
![target_empty_ok](https://user-images.githubusercontent.com/75318923/141797200-3d9c6036-ab49-4470-b91d-c884fd53b708.png)
:

**Comment by awinia-github** [comment]
not reproducible

**Comment by Zlin526F** [comment]
This error occure, if I create a new mamba environment,  install spyder=5.3 and the latest semi-ate. After starting spyder and opening an existing project, set the Hardware and Base Comboxes, than the target box is empty. I have to restart spyder. 
Only then do I have a selection in the target.
