### ISSUE TITLE
The instance.apply_configuration in the common.py is only called if a configuration.json file exist

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#115]
The instance.apply_configuration in the common.py is only called if a configuration.json file exist. 
But I think we need also a call for a default configuration.

![apply_configuration](https://user-images.githubusercontent.com/75318923/147685207-4ae8500a-e696-4ece-9bae-7ef692afd390.png)

**Comment by awinia-github** [comment]
apply_configuration must be called in all cases
