### ISSUE TITLE
sammy -h -> get an exception 

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#129]
![image](https://user-images.githubusercontent.com/75318923/152781396-4eb21ef2-8c12-4fb2-8337-1f7685c23851.png)

**Comment by nerohmot** [comment]
... you see now why I insist on the packaging with Awinia?

**Comment by Zlin526F** [comment]
yes, sometimes it really hurts.

I try to get an existing tb_ate running again with sammy, but with 'sammy generate test_target' i get an exception, too:
![image](https://user-images.githubusercontent.com/75318923/152792194-a25b1869-d0af-42ed-a8dd-c29efdabe03c.png)

**Comment by Zlin526F** [comment]
and yet another error
sammy build isn' t running together with maxiconda:
sammy.ps1: line 10:
else
{
    Invoke-Expression "conda create --name sammybuildn"
    Invoke-Expression "conda activate sammybuildn"
    Invoke-Expression "conda install --file run.txt"
    Invoke-Expression "pyinstaller --onefile --console --clean --distpath .\ sammy.py"
    Invoke-Expression "conda deactivate"
}

-> change conda to mamba

**Comment by nerohmot** [comment]
Yes, that should be "mamba create -n sammybuildn" !

**Comment by Zlin526F** [comment]
By incorrect deletion, check-in and updates with svn,  the database can be destroyed.
To find this errors in the database, it will be helpful to add in ATE\sammy\verbs\generate.py in line 133:
            try:
                testdefinition = Test.get(self.file_operator, test_target.test, test_target.hardware, test_target.base).definition
            except Exception:
               print(f"        Error: couldn't generate {test_target.hardware}, {test_target.base}, {test_target.test}") 
               continue
--> no exception occure, only an Error. With the information you can repair the database by hand.

**Comment by Zlin526F** [comment]
ok in Version 1.03
