### ISSUE TITLE
To arrange the necessary autoscript to the hardware not to every flow

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#130]
The *_auto_script handle the termination and exceptions.
It would be more logical if we assign this file to the hardware. 
Right now, we need to create one for each flow. So if you create a new flow, you also have to adjust the _auto_script again and again. I think this make no sense.

**Comment by nerohmot** [comment]
🤪 help stupid me to remember again what is the `auto script` doing ?

**Comment by Zlin526F** [comment]
You can define there what should be done after an exception or after a terminate.
For example, 
- quit a usb device cleanly
- set your smu to 0V, 
- write your setup to a file 
and so on

**Comment by awinia-github** [comment]
#173 will solve this issue
