### ISSUE TITLE
stdf/stdr.py: rounding in _unpack_item isn't correct.

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#137]
I have a stdf-file with a small value in PTR|1004:
![image](https://user-images.githubusercontent.com/75318923/154478817-6981a2f6-b06d-47a1-9c95-2e19280c4c91.png)

If the record is read, then the value is 0.0 after rounding in the stdf/str.py
![image](https://user-images.githubusercontent.com/75318923/154478615-d76a2b9c-8985-4f67-a45f-f1987e5c770e.png)

In line 1615: result is read correct  = 5.810000036632346e-09
and than in the next rows: 
   leading = 0.0
   len_lead = 3
   result = 0.0   -> wrong value

**Comment by seimit** [comment]
Hello,
Based on provided screenshot, I can assume that you are using old version of STDF library.
In the STDF issue 30 (https://github.com/Semi-ATE/STDF/issues/30) from 6 Oct 2021 was introduced static variable STDR.float_prec_digits with default value -1. If default value is used, there is no round when the float variable is stored in the STDF file. You can use this variable to round to exact number after the decimal point.
