### ISSUE TITLE
in the result stdf-file the PTR['TEST_FLG'] is always 1 

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#141]
the call of 'generate_PTR' does not match with the function definition, or is set to 'false'

![image](https://user-images.githubusercontent.com/75318923/155364911-b1a48003-d085-4912-beb1-368457a09c9b.png)

**Comment by awinia-github** [comment]
I think the check for **is_pass** can be simplified to: **ptr_record['TEST_FLG'] == 0**

**Comment by awinia-github** [comment]
This issue was fixed in with PR #152
