### ISSUE TITLE
MiniSCT "plugin" to make the MiniSCT available to Semi-ATE system.

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/Semi-ATE#158]

**Comment by Zlin526F** [comment]
@awinia-github  : I generated a new pull request for this issue

**Comment by nerohmot** [comment]
... well, not a PR yet, but a branch (issue_158) ;-)

**Comment by nerohmot** [comment]
OK, confirmed, the CI of the `issue_158` generated the packages, but in the `semi-ate-testers` the `semi-ate-msct` tester is not present!
