### ISSUE TITLE
No issue - only learning

### ISSUE THREAD

**Issue by FriSchl** [Semi-ATE/Semi-ATE#167]
alles wird gut

**Comment by Zlin526F** [comment]
bestimmt :-)

**Comment by Zlin526F** [comment]
Wenn ein Issue bearbeitet worden ist, und z. Bsp nach einm  Pull request der Fehler nicht mehr vorhanden ist, schliesst man den Issue mit 'Close with comment'.  
Auch wenn man feststellt, der Issue war vielleicht doch gar kein 'Bug' sondern ein 'Feature'  schliesst man den Issue.

**Comment by FriSchl** [comment]
Am Ende ist tatsächlich alles gut..
