### ISSUE TITLE
Add conda installation to README.md

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/Semi-ATE#176]
[link](https://www.google.com/)
- topic 1
- topic 2
- [markdown](https://en.wikipedia.org/wiki/Markdown)

![image](https://user-images.githubusercontent.com/3516972/174799146-781444bd-b059-4f92-999b-fbb32fa4c239.png)

**Comment by awinia-github** [comment]
@nerohmot  why do you provide this link?

**Comment by awinia-github** [comment]
Yes I will do it

**Comment by awinia-github** [comment]
![image](https://user-images.githubusercontent.com/60256982/176120362-fd0216f2-91ab-480c-94f7-67d77caca1c3.png)
