### ISSUE TITLE
Please update documentation docs/semi-ate-applications.md and docs/project/GettingStarted.md

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#213]
In the file https://github.com/Semi-ATE/Semi-ATE/blob/master/docs/semi-ate-applications.md the  description from master_config_file.json isn't correct:
    "filesystemdatasource.path":     should be:  "filesystemdatasource_path"
    "filesystemdatasource.jobpattern":  should be   "filesystemdatasource_jobpattern":
     "tester_type": "Semi-ATE Master Single Tester",   should be:   "tester_type": "Semi_ATE Master Single Tester",

I think the description in semi-ate-application replace 
https://github.com/Semi-ATE/Semi-ATE/blob/master/docs/project/GettingStarted.md ?

If not please update GettingStarted.md

**Comment by Sesamepas** [comment]
When accessing the Releases page at https://github.com/Semi-ATE/MSCT-WebUI/releases, the page returns a 404 error. If the project has been moved to a new location or renamed, please update the semi-ate-applications.md file accordingly to reflect these changes.
