### ISSUE TITLE
Implement Drag & Drop function from MappingList to QTableView

### ISSUE THREAD

**Issue by hari999333** [Semi-ATE/Semi-ATE#265]
- To insert 'No' field in MappingList
- Implement Drag & Drop betwwen MappingList and QTableView
- Generate an updated '.json' file after editing the the QTableView and save it somewhere in the project directory

**Comment by hari999333** [comment]
Hello, the following enhancements were made :

	1. Drag & Drop is implemented in both QTableWidget and QListWidget.
	2. The headers in the QTableWidget can be saved separately as a JSON file with their matching dictionary keys.
	3. The saved JSON file can be loaded later to get the headers in the QTableWidget.

Now, the code needs to be reviewed ...

**Comment by Zlin526F** [comment]
Hello, 
please commit and push your changes in your branch '265-implement....'

**Comment by hari999333** [comment]
Hello ... The enhancement mentioned in the previous comments is done with latest master in the branch "265-implement-drag-drop-function-from-mappinglist-to-qtableview-1new_branch".

Now the code needs to be reviewed. Commit ID is '9a5b05a95b29c3684a0161c9a2a9f37765529931' ...

**Comment by Zlin526F** [comment]
Hello,
I used the branch 265-implement-drag-drop-function-from-mappinglist-to-qtableview-1new_branch, but it didn't run correctly.
Please check some points:

1. when I open an exel-sheet that does not have a column named 'Test name' I get an exception in line 345 from the ExcelTestWizard.py.

The Excel sheet looks like:
![image](https://user-images.githubusercontent.com/75318923/210403901-f65e1b90-cbd3-4a7a-9999-08042699d404.png)

if you change the code like i did it will run, but I think the verify should not use mappingATEDic? :
![image](https://user-images.githubusercontent.com/75318923/210405204-5bcea7bc-c90e-484c-a6c7-9b5d2ccf111a.png)

2.  you can drop a selected test parameter anywhere, so not in the 1st line. 
![image](https://user-images.githubusercontent.com/75318923/210405459-035c2846-220e-49c8-a74b-5a33beace7c5.png)

3. the function verify is not correct, it use mappingATEDic, but this will not be changed if you drag and drop the parameters?
