### ISSUE TITLE
file_configutation_tester_org.py and labctrl.py needs updates

### ISSUE THREAD

**Issue by duke790** [Semi-ATE/Semi-ATE#338]
Semi-ATE\Semi-ATE\src\Plugins\semi_ate_testers\semi_ate_testers\testers\file_configuration_tester.py:

1.) imort json is not needed (used)
2.) self.hw_path should have one parent less and a path separator at the end:
![image](https://github.com/Semi-ATE/Semi-ATE/assets/166118445/b42fc711-3b15-406f-ad16-f7451ad2b66d)
3.) give a warning in case the default testerconfig file is not used:
4.) add self.logger instances
![image](https://github.com/Semi-ATE/Semi-ATE/assets/166118445/a2e26e26-d4c5-4388-af47-f81c848052a7)
5.) correct pythonPath
![image](https://github.com/Semi-ATE/Semi-ATE/assets/166118445/ac993dc1-2619-49ed-b8e3-28ffafd071b2)
6.) setattr fixes
![image](https://github.com/Semi-ATE/Semi-ATE/assets/166118445/f6dcf71c-a32d-403b-b316-010a569c52f6)

Semi-ATE\Semi-ATE\src\ATE_spyder\ate_spyder_lab_control\labml_adjutancy\ctrl\labctrl.py:

1.) initialze self.parent to init
![image](https://github.com/Semi-ATE/Semi-ATE/assets/166118445/b41be37c-6093-4512-9f80-162440590664)
2.) remove case self.parent is None
![image](https://github.com/Semi-ATE/Semi-ATE/assets/166118445/631fc72b-679b-406d-824e-76560df3f92d)
3.) update setShortNames
![image](https://github.com/Semi-ATE/Semi-ATE/assets/166118445/84208e38-ffc4-4342-a90b-7ec051d047b8)

**Comment by Zlin526F** [comment]
This is done in https://github.com/Semi-ATE/Semi-ATE/tree/322-rename_test

**Comment by Zlin526F** [comment]
solve
