### ISSUE TITLE
Instrument init

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/Semi-ATE#35]
...

**Comment by modelltechnik-jung** [comment]
in tests no access to common.py, variable *_instance =get_plugin_manager().hook.get_instrument(...)

e.q.:
import src.HW1.FT.common     # create new instance, so no access to orignal instance possible

**Comment by Zlin526F** [comment]
done with the pull-request  [Import 2020 12 04](https://github.com/awinia-github/Semi-ATE/tree/import-2020-12-04)
