### ISSUE TITLE
Maskset Wizard : create without name possible

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#37]
@awinia-github 
 it is possible to create a Maskset without a name. After creating and saving, no edit from the empty name is possible.

![noname](https://user-images.githubusercontent.com/75318923/100754923-e8bd8e00-33eb-11eb-9af6-c1ed6c3829e8.png)

**Comment by awinia-formicronas** [comment]
SPYD-422
