### ISSUE TITLE
Add configurable parameter in the Edit Hardwaresetup Wizard/Instruments for the function call

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#39]
It would be helpful to add one configurable parameter in the Hardwaresetup Wizard, Register Instruments which is include in the function call:
TCCLabor_Instruments_instance = get_plugin_manager().hook.get_instrument(instrument_name="TCCLabor.Instruments", parameter='blabla)[0]

![parameter](https://user-images.githubusercontent.com/75318923/101340680-58b29500-3880-11eb-8cb9-3ca10a4ffb9b.png)

**Comment by awinia-formicronas** [comment]
SPYD-423
