### ISSUE TITLE
Add CI and protect master branch

### ISSUE THREAD

**Issue by goanpeca** [Semi-ATE/Semi-ATE#4]

**Comment by nerohmot** [comment]
the PR for the CI I merged, it was failing because pre-commit (and pytest) failed locally already, I fixed that first and then merged your PR.

**Comment by goanpeca** [comment]
Yes @nerohmot, added protection to the master branch. So from now on let's try to always open PRs :-) 

Thanks for the merge!

**Comment by nerohmot** [comment]
@goanpeca 
does this `protect master branch` looks right ?
![image](https://user-images.githubusercontent.com/3516972/88516921-58f77580-cfee-11ea-91fd-9f0f0faec5c9.png)

**Comment by goanpeca** [comment]
Hi Tom

Yes you can configure like that
