### ISSUE TITLE
no logger available in the Context.__init__

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#41]
Beim initialisieren der Instrumente  ist kein logging möglich.
In der class Context im File 'common.py' sollter der Logger bei 
   self.TCCLabor_Instruments_instance = get_plugin_manager().hook.get_instrument(instrumenent_name="TCCLabor.Instruments) mit übergeben werden können.

**Comment by awinia-formicronas** [comment]
SPYD-437

**Comment by Zlin526F** [comment]
Der Logger ist mit dem  Delivery-2021-01-18 jetzt auch im Plugin verfügbar.
Logging innerhalb des Spyders werden ausgeben,  aber eine Ausgabe in das Logfile  oder mqtt-Nachrichten erfolgen nicht.
Erst wenn die Tests ablaufen, erfolgt dann auch eine Ausgabe in das Logfile mit mqtt-Nachrichten.
