### ISSUE TITLE
comments in tests from the parameter are not correct

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#42]
Der Kommentar in den automatisch erstelltem Teil der tests ist nicht ganz richtig:
    <do_not_touch>
    Set Matrix to Position 1
    Input Parameter | Shmoo | Min | Default | Max | Unit | fmt
    ----------------+-------+-----+---------+-----+------+----
    ip.Temperature  |  Yes  | -40 |   25    | 170 | °C | .0f

    Parameter         | LSL | (LTL) |  Nom  | (UTL) | USL  | Unit | fmt
    ------------------+-----+-------+-------+-------+------+------+----
    op.passfail       |  -∞ | 0.000 | 0.000 | 0.000 | +∞   | ˽ | .3f
    </do_not_touch>
    ''' 

richtig wäre:
     ip.*i_Temperature
     op.o_*passfail 
heissen.

**Comment by awinia-formicronas** [comment]
SPYD-444
