### ISSUE TITLE
no information if Exception occured in tests

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#43]
Wenn eine Exception innerhalb eines Test auftritt, bekommt man keinerlei Information darüber. 
Es wird nur eine Softbin, Hardbin nummer ausgegeben.
Das debuggen ist dadurch doch sehr aufwändig.
Hilfreich wäre es wenn die Exeception information als logging.error(eception_information) ausgeben wird.

**Comment by awinia-formicronas** [comment]
SPYD-436
