### ISSUE TITLE
mqtt message if test starts, with information about the testname will be helpful 

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#44]
Eine mqtt nachricht wenn ein test anfängt mit dem Namen des aktuellen testfiles wäre gut.
Wenn dann ein Test fertig ist, so könnte man noch die Zeitdauer dieses einzelnen Tests senden.

Klar könnte man sich das auch in jedem Test einbauen, aber wenn das automatisch vom Framework gemacht werden würde, spart man sich Code und Zeit.

**Comment by awinia-formicronas** [comment]
SPYD-440

**Comment by Zlin526F** [comment]
Mit Lieferung vom 10.3.2021 vorhanden.

Es wäre gut die Nachricht von Debug auf Info zu setzen.

**Comment by Zlin526F** [comment]
Mit Import-2021-04-08 noch nicht geändert. 
Wenn Level Info zu hoch, dann sollte es ein Level zwischen Measure und Info sein.
