### ISSUE TITLE
after send terminate signal, logging handler should be closed

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#46]
Wenn man einem laufendem Testprogramm ein 'MQTT terminate' schickt so wird zwar das Programm beendet. Aber  das zugehörige log-file wird nicht geschlossen. 
Das führt dann bei einem Neustart des Testprogrammes dazu, dass ein logging sowohl in das alte als auch in das neue log-file geschrieben wird. In der Console steht dann mehrmals immer die gleiche Meldung.

siehe auch:
anaconda3\envs\semi-ate\lib\__init__.py :    c.handlers  enthält mehrere LogHandler:
[<LogHandler stderr (DEBUG)>, 
<RotatingFileHandler C:\Users\appslab\ATE\HANA54_1\src\HW0\FT\log\20201223-174403_TestApp0.log (DEBUG)>,
<LogHandler stderr (DEBUG)>, 
<RotatingFileHandler C:\Users\appslab\ATE\HANA54_1\src\HW0\FT\log\20201223-175642_TestApp0.log (DEBUG)>]

**Comment by awinia-formicronas** [comment]
SPYD-438
-> Das sieht ein bisschen so aus, als würde der Spyder Debugger den Interpreter, in dessen Kontext das Programm läuft nicht richtig beenden.
