### ISSUE TITLE
STDF Tests fail on windows

### ISSUE THREAD

**Issue by awinia-github** [Semi-ATE/Semi-ATE#63]
#   Test ATDF output
        assert inst.to_atdf() == expected_atdf
    
>       os.remove(tf.name)
E       PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\WINDOWS\\TEMP\\tmpclm0q1hw'
tests\ATE\data\STDF\test_MPR.py:382: PermissionError

The handling of temporary files on windows seems to be different, leading to this problem. However: The tests don't really have to use tempfiles, instead it would be cleaner if the STDFRecTest class would use a plain bytearray instead of a file.

**Comment by nerohmot** [comment]
Don't use a temporary file, just keep the data in memory, that doesn't hurt.
