### ISSUE TITLE
Test Program Wizard: select and place Test is no correct

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#88]
![select1](https://user-images.githubusercontent.com/75318923/111158817-c580ae00-8598-11eb-9b25-5fd1d1a6f069.jpg)
![select2](https://user-images.githubusercontent.com/75318923/111158826-c87b9e80-8598-11eb-908e-bd1c0f6fceea.jpg)

**Comment by awinia-github** [comment]
SPYD-537
