### ISSUE TITLE
Edit Hardwaresetup Wizard 

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#89]
Wenn man nach einem Spyder start, den 'Edit Hardwaresetup Wizard' zum zweiten Mal aufruft kommt ein internal Spyder problem:
![edithardwaresetup](https://user-images.githubusercontent.com/75318923/111335415-a8b9a880-8674-11eb-85bb-b88d79be8d05.png)

**Comment by awinia-github** [comment]
Bitte aktuellere Pythonversion  (>= 3.8) benutzen, dann soltle das Problem verschwinden.

**Comment by Zlin526F** [comment]
ok gemacht,  funktioniert mit Pyhton=3.8
