### ISSUE TITLE
Error in installation-script setup.ps1

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#90]
Mit der neusten Version wird spyder unter Semi-ATE installiert. 
Dann ist aber der Pfad für die Abhängigkeit im setup.ps1 falsch:

do you want to install spyder dependencies [y/n]: y
Set-Location : Der Pfad "C:\Users\appslab\ATE\spyder" kann nicht gefunden werden, da er nicht vorhanden ist.
In C:\Users\appslab\ATE\Semi-ATE\setup.ps1:141 Zeichen:9
+         Set-Location -Path $spyder2_location
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\appslab\ATE\spyder:String) [Set-Location], ItemNotFoundExcepti
   on
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

CondaFileIOError: 'requirements/conda.txt'. [Errno 2] No such file or directory: 'requirements/conda.txt'

install requirements
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

**Comment by awinia-github** [comment]
SPYD-536
