### ISSUE TITLE
Testnames or flows with '-' are not allowed in python

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#99]
![image](https://user-images.githubusercontent.com/75318923/118256197-87770c00-b4ad-11eb-8990-601cf603f6cf.png)

![image](https://user-images.githubusercontent.com/75318923/118255975-36671800-b4ad-11eb-83f0-8a2c4f9661ad.png)

**Comment by awinia-github** [comment]
SPYD-562
